name: 24/7 Stream
on:
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install yt-dlp
      - name: Start Live Stream
        run: |
          VIDEO_URL=$(yt-dlp -g -f "best" "https://www.youtube.com/watch?v=Z0sMcD8mh28")
          ffmpeg -re -stream_loop -1 -i "$VIDEO_URL" -c:v libx264 -preset veryfast -b:v 2000k -maxrate 2000k -bufsize 4000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -f flv "rtmp://a.rtmp.youtube.com/live2/b55a-s2zd-de1q-5v0v-e13y"
